/** Font Awesome Pro duotone / brand icon names */
export const FA_ICONS = {
  shield: "fa-shield-halved",
  store: "fa-shop",
  briefcase: "fa-briefcase",
  car: "fa-car-side",
  phone: "fa-mobile-screen-button",
  sparkles: "fa-wand-magic-sparkles",
  mask: "fa-mask",
  discord: { brand: true, name: "fa-discord" },
  download: "fa-download",
  key: "fa-key",
  city: "fa-city",
  "badge-check": "fa-badge-check",
  gamepad: "fa-gamepad",
  users: "fa-users",
  "clipboard-check": "fa-clipboard-check",
  plug: "fa-plug",
  sun: "fa-sun",
  moon: "fa-moon",
  "circle-info": "fa-circle-info",
  "circle-check": "fa-circle-check",
  "circle-xmark": "fa-circle-xmark",
  link: "fa-link",
  server: "fa-server",
  dice: "fa-dice",
  building: "fa-building",
  "user-shield": "fa-user-shield",
  gem: "fa-gem",
  route: "fa-route",
  gauge: "fa-gauge-high",
  "arrow-down": "fa-arrow-down",
  house: "fa-house",
  user: "fa-user",
  ambulance: "fa-truck-medical",
};
